### PR TITLE
New chart : kube-gcp

### PR DESCRIPTION
**Pull request by nlamirault**
#### What this PR does / why we need it:

A new chart for GCP experiments

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by neelanjan00** [comment]
Experiment run using helm chart for `gcp-vm-instance-stop`: 
```
W0117 11:38:46.093452       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-01-17T11:38:46Z" level=info msg="Experiment Name: gcp-vm-instance-stop"
time="2022-01-17T11:38:46Z" level=info msg="[PreReq]: Procured the ENV for the gcp-vm-instance-stop experiment"
time="2022-01-17T11:38:48Z" level=info msg="[PreReq]: Updating the chaos result of gcp-vm-instance-stop experiment (SOT)"
time="2022-01-17T11:38:50Z" level=info msg="The instance information is as follows" Chaos Duration=30 Chaos Namespace=default Instance Names=rhel-7 Zones=us-central1-a
time="2022-01-17T11:38:50Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2022-01-17T11:38:50Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2022-01-17T11:38:50Z" level=info msg="[Info]: The instances under chaos(IUC) are: [rhel-7]"
time="2022-01-17T11:38:50Z" level=info msg="[Status]: VM instance is in running state"
time="2022-01-17T11:38:50Z" level=info msg="[Info]: Target instanceID list, [rhel-7]"
time="2022-01-17T11:38:50Z" level=info msg="[Chaos]: Stopping the desired VM instance"
time="2022-01-17T11:38:51Z" level=info msg="Stopping VM instance:" InstanceZone=us-central1-a InstanceName=rhel-7
time="2022-01-17T11:38:51Z" level=info msg="[Wait]: Wait for VM instance 'rhel-7' to get in stopped state"
time="2022-01-17T11:38:51Z" level=info msg="[Status]: Checking VM instance status"
time="2022-01-17T11:38:51Z" level=info msg="The instance state is RUNNING"
time="2022-01-17T11:38:53Z" level=info msg="The instance state is STOPPING"
time="2022-01-17T11:38:55Z" level=info msg="The instance state is STOPPING"
time="2022-01-17T11:38:58Z" level=info msg="The instance state is STOPPING"
time="2022-01-17T11:39:00Z" level=info msg="The instance state is STOPPING"
time="2022-01-17T11:39:02Z" level=info msg="The instance state is STOPPING"
time="2022-01-17T11:39:04Z" level=info msg="The instance state is STOPPING"
time="2022-01-17T11:39:06Z" level=info msg="The instance state is STOPPING"
time="2022-01-17T11:39:08Z" level=info msg="The instance state is TERMINATED"
time="2022-01-17T11:39:10Z" level=info msg="[Wait]: Waiting for chaos interval of 30s"
time="2022-01-17T11:39:40Z" level=info msg="[Chaos]: Starting back the VM instance"
time="2022-01-17T11:39:41Z" level=info msg="Starting VM instance:" InstanceName=rhel-7 InstanceZone=us-central1-a
time="2022-01-17T11:39:41Z" level=info msg="[Wait]: Wait for VM instance 'rhel-7' to get in running state"
time="2022-01-17T11:39:41Z" level=info msg="[Status]: Checking VM instance status"
time="2022-01-17T11:39:42Z" level=info msg="The instance state is TERMINATED"
time="2022-01-17T11:39:44Z" level=info msg="The instance state is STAGING"
time="2022-01-17T11:39:46Z" level=info msg="The instance state is STAGING"
time="2022-01-17T11:39:48Z" level=info msg="The instance state is STAGING"
time="2022-01-17T11:39:50Z" level=info msg="The instance state is STAGING"
time="2022-01-17T11:39:52Z" level=info msg="The instance state is RUNNING"
time="2022-01-17T11:39:54Z" level=info msg="[Confirmation]: gcp-vm-instance-stop chaos has been injected successfully"
time="2022-01-17T11:39:54Z" level=info msg="[Info]: The instances under chaos(IUC) are: [rhel-7]"
time="2022-01-17T11:39:54Z" level=info msg="[Status]: Checking VM instance status"
time="2022-01-17T11:39:55Z" level=info msg="The instance state is RUNNING"
time="2022-01-17T11:39:57Z" level=info msg="[Status]: VM instance is in running state (post chaos)"
time="2022-01-17T11:39:57Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2022-01-17T11:39:57Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2022-01-17T11:39:57Z" level=info msg="[The End]: Updating the chaos result of gcp-vm-instance-stop experiment (EOT)"
```

**Comment by neelanjan00** [comment]
Experiment run using helm chart for `gcp-vm-disk-loss`:
```
W0117 11:47:10.227039       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-01-17T11:47:10Z" level=info msg="Experiment Name: gcp-vm-disk-loss"
time="2022-01-17T11:47:10Z" level=info msg="[PreReq]: Getting the ENV for the gcp-vm-disk-loss experiment"
time="2022-01-17T11:47:12Z" level=info msg="[PreReq]: Updating the chaos result of gcp-vm-disk-loss experiment (SOT)"
time="2022-01-17T11:47:14Z" level=info msg="The volume information is as follows" Sequence=parallel Volume IDs=test-disk Zones=us-central1-a
time="2022-01-17T11:47:14Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2022-01-17T11:47:14Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2022-01-17T11:47:14Z" level=info msg="The selected disk volume is:" VolumeType=pd-balanced Status=READY InstanceName=rhel-7 VolumeName=test-disk
time="2022-01-17T11:47:15Z" level=info msg="[Chaos]: Detaching the disk volume from the instance"
time="2022-01-17T11:47:15Z" level=info msg="Detaching disk having:" Device=test-disk InstanceName=rhel-7 Status=RUNNING
time="2022-01-17T11:47:15Z" level=info msg="[Wait]: Wait for disk volume detachment for volume test-disk"
time="2022-01-17T11:47:15Z" level=info msg="[Status]: Checking disk volume status for detachment"
time="2022-01-17T11:47:15Z" level=info msg="The selected disk volume is:" Status=READY InstanceName=rhel-7 VolumeName=test-disk VolumeType=pd-balanced
time="2022-01-17T11:47:15Z" level=info msg="[Info]: The volume state is attached"
time="2022-01-17T11:47:17Z" level=info msg="The selected disk volume is:" VolumeName=test-disk VolumeType=pd-balanced Status=READY InstanceName=rhel-7
time="2022-01-17T11:47:17Z" level=info msg="[Info]: The volume state is attached"
time="2022-01-17T11:47:20Z" level=info msg="[Info]: The volume state is detached"
time="2022-01-17T11:47:22Z" level=info msg="[Wait]: Waiting for the chaos interval of 30s"
time="2022-01-17T11:47:52Z" level=info msg="[Chaos]: Attaching the disk volume to the instance"
time="2022-01-17T11:47:53Z" level=info msg="Attaching disk having:" Device=test-disk InstanceName=rhel-7 Status=RUNNING
time="2022-01-17T11:47:53Z" level=info msg="[Wait]: Wait for disk volume attachment for volume test-disk"
time="2022-01-17T11:47:53Z" level=info msg="[Status]: Checking disk volume status for attachment"
time="2022-01-17T11:47:53Z" level=info msg="[Info]: The volume state is detached"
time="2022-01-17T11:47:55Z" level=info msg="The selected disk volume is:" VolumeType=pd-balanced Status=READY InstanceName=rhel-7 VolumeName=test-disk
time="2022-01-17T11:47:55Z" level=info msg="[Info]: The volume state is attached"
time="2022-01-17T11:47:57Z" level=info msg="[Confirmation]: gcp-vm-disk-loss chaos has been injected successfully"
time="2022-01-17T11:47:57Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2022-01-17T11:47:57Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2022-01-17T11:47:57Z" level=info msg="The selected disk volume is:" VolumeName=test-disk VolumeType=pd-balanced Status=READY InstanceName=rhel-7
time="2022-01-17T11:47:57Z" level=info msg="[The End]: Updating the chaos result of gcp-vm-disk-loss experiment (EOT)"
```

**Review by neelanjan00 — APPROVED** [review]
LGTM, all the charts are working correctly when tested. CC: @uditgaurav @nlamirault

**Review by uditgaurav — APPROVED** [review]

**Review by Jasstkn — CHANGES_REQUESTED** [review]
Hi.

Please, add the chart name here: https://github.com/litmuschaos/litmus-helm/blob/master/.circleci/config.yml#L113

**Comment by nlamirault** [comment]
Done @Jasstkn

**Comment by uditgaurav** [comment]
Should we also update [this condition](https://github.com/litmuschaos/litmus-helm/blob/f33b7edbf22c82c4ad3e8941ac6553b5ceaa8ce6/.circleci/config.yml#L78) in ci. @nlamirault

**Review by Jonsy13 — APPROVED** [review]

**Pull request merged**
