### PR TITLE
add tolerations to litmuschaos_crd.yaml

### PR DESCRIPTION
**Pull request by nikolay-o**
Signed-off-by: Nikolay Osmolovsky <nikolay.osmolovsky@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by ksatchit** [comment]
Thanks @nikolay-o ! If possible, could you also add the validations for `tolerations ` in the .spec.components.runner in the ChaosEngine too in this PR? 

image

**Comment by nosmolovskiy** [comment]
@ksatchit thanks for review.
I tried to add anyOf validation like
`
...
                                    effect:
                                     description: ...
                                     type: string
+                                    anyOf:
+                                    - type: string
...
`
but got error on apply.

`
The CustomResourceDefinition "chaosengines.litmuschaos.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[experiments].items.properties[spec].properties[components].properties[tolerations].items.properties[effect].anyOf[0].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[experiments].items.properties[spec].properties[components].properties[tolerations].items.properties[tolerationSeconds].anyOf[0].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[experiments].items.properties[spec].properties[components].properties[tolerations].items.properties[value].anyOf[0].type: Forbidden: must be empty to be structural
`

If anyOf is not what you talked about please clarify what is needed.

**Comment by ispeakc0de** [comment]
Hi @nosmolovskiy,
Can you please resolve the conflicts and also add toleration inside `.spec.components.runner.tolerations`  [refer](https://github.com/litmuschaos/chaos-operator/blob/master/deploy/chaos_crds.yaml#L88)

**Comment by nikolay-o** [comment]
looks like this changes merged as part of
https://github.com/litmuschaos/litmus-helm/pull/124

I think this PR could be closed

**Pull request closed without merging**
