### PR TITLE
Added latest CRD validations, and clusterrole for v1.4.x

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>

#### What this PR does / why we need it:

- Added latest CRD Validations
- Added Clusterrole permission for Admission Controllers.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by ksatchit** [comment]
@rahulchheda this is from a branch -- can you submit from your fork?

**Comment by ksatchit** [comment]
Also please check the lint failure. You may also want to bump up image versions in values yaml to 1.4 for the components and also chart version cc: @Jasstkn

**Comment by Jasstkn** [comment]
@rahulchheda could you bump chart and app version in Chart.yaml? And increase it in README as well, please.

**Comment by rahulchheda** [comment]
Seems like I did it without fork :p.
Closing this, and creating a new PR

**Pull request closed without merging**
