### PR TITLE
Server role updated

### PR DESCRIPTION
**Pull request by radudd**
Signed-off-by: Radu Domnu <radu.domnu@gmail.com>

#### What this PR does / why we need it:

Currently cluster registration fails in namespace mode, as the server role doesn't have enough permissions to deploy all the required resources.
In the current role, only a set of the required permissions are defined.

The resources that need to be provisioned by the server service account are defined here: https://github.com/litmuschaos/litmus/tree/abf1bf655a7495d51609bd97b388dfcb69a2efd4/litmus-portal/graphql-server/manifests/namespace. So all of the resources specified here need to be included in the role.

Moreover, one of the resources required to be provisioned by the serviceaccount are Roles, and the provisioned role cannot have more permissions than the role which is providing the permissions to create roles. 
The list of the roles that need to be provisioned are here: https://github.com/litmuschaos/litmus/blob/abf1bf655a7495d51609bd97b388dfcb69a2efd4/litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml

One of the roles that need to be provisioned already requires all permissions in that namespace:
https://github.com/litmuschaos/litmus/blob/abf1bf655a7495d51609bd97b388dfcb69a2efd4/litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml#L150-L162. Hence the server role requires the same.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by rajdas98** [comment]
Hi @radudd , there are some merge conflicts in your PR.

**Comment by ksatchit** [comment]
We might need the exact list of resources, this is what we have tested w/ in the manifest based install.

**Review by ksatchit — APPROVED** [review]

**Comment by radudd** [comment]
> Hi @radudd , there are some merge conflicts in your PR.

Fixed

**Review by ishangupta-ds — COMMENTED** [review]
I think the issue has already been fixed.

**Comment by radudd** [comment]
> I think the issue has already been fixed.

I saw now. It was actually fixed just before this PR with https://github.com/litmuschaos/litmus-helm/pull/116
Thanks

**Pull request closed without merging**
