### PR TITLE
Upgraded litmus charts to 2.12.0 ChaosCenter

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Vedant <vedant.srotria@harness.io>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Review by Adarshkumar14 — APPROVED** [review]

**Comment by Jasstkn** [comment]
@Jonsy13 hi. Did you check deploy locally? Pipelines are failing.

**Comment by Jonsy13** [comment]
Hi @Jasstkn , yes, we will have to wait for images. The images are in building phase.

**Review by Jasstkn — APPROVED** [review]

**Comment by Jasstkn** [comment]
@Jonsy13 lgtm. should i merge it?

**Comment by Jonsy13** [comment]
@Jasstkn Yes we can merge it now. Have tested it.

**Pull request merged**
