### PR TITLE
Add README for helm-chart

### PR DESCRIPTION
**Pull request by Jasstkn**
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>

### CODE REVIEW

**Comment by Jasstkn** [comment]
@ksatchit hello! I'm not sure if I need to bump chart version. Also, maybe there is an additional info which should be placed in README from your point of view?

**Comment by ksatchit** [comment]
Thank you for the PR @Jasstkn ! The chart version is accurate (we are still working on 1.3.1!). 

I see that the README is for the charts (litmus) folder to explain to the intent is to explain/summarize the content of the values.yaml for the user with current default values, which is cool.

**Comment by ksatchit** [comment]
You might want to update this once you have the exporter deployment included into the templates - the values might get a few more entries. But at this point - it looks great. Thanks again.

**Comment by Jasstkn** [comment]
> Thank you for the PR @Jasstkn ! The chart version is accurate (we are still working on 1.3.1!).
> 
> I see that the README is for the charts (litmus) folder where the intent is to explain/summarize the values.yaml for the user with current default values, which is cool.

Yes, it's common practice and it improves user-experience. 
I used helm-docs plugin which is awesome for init some docs and maintain it further. 

If you ok with this PR, feel free to merge this PR.

**Comment by Jasstkn** [comment]
> the exporter deployment included into the templates - the values might get a few more entries. But at this point - it looks great. Thanks again.

Yep, I'm going to prepare that deployment, service and service monitor during the closest few hours.

**Pull request merged**
