### PR TITLE
Replace custom portalNamespace to .Release.Name

### LINKED ISSUE #77: Allow users to define namespace for litmus-portal
We need to allow users to define namespace for litmus-portal. It's impossible for now because of: https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus-portal/values.yaml#L6

### PR DESCRIPTION
**Pull request by Jasstkn**
#### What this PR does / why we need it:
- Allow users to deploy litmus-portal in whatever namespace they want without changing chart or pass additional values
- Added readme

#### Which issue this PR fixes
  - fixes #77 

#### Checklist
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rajdas98** [comment]
Hi @Jasstkn, Can you add a NOTES.txt 
```
Thank you for installing {{ .Chart.Name }} 😀

Your release is named {{ .Release.Name }}.

Visit https://docs.litmuschaos.io/docs/getstarted/ to find more info.
```

**Review by rajdas98 — APPROVED** [review]

**Comment by rajdas98** [comment]
Hi @Jasstkn, Have to install litmusportal with these changes?

**Comment by Jasstkn** [comment]
> Hi @Jasstkn, Have you install litmusportal with these changes?

Hi! Easy:
`helm install litmus-portal <chart> -n <namespace>`, or it will be automatically installed in the current context in your kubeconfig (usually default).

**Comment by rajdas98** [comment]
Okay @Jasstkn , I was just checking if it is working with these changes or not.

**Comment by Jasstkn** [comment]
> Okay @Jasstkn , I was just checking if it is working with these changes or not.

Did you face any issues? I'm able to deploy it successfully..

**Review by ksatchit — APPROVED** [review]

**Comment by ksatchit** [comment]
Thank you for the PR @Jasstkn !

**Pull request merged**
