### PR TITLE
Respect service type and make clusterIP default

### LINKED ISSUE #256: Litmus does not honor service.type field when ingress is enabled
We are hosting litmus on an kubernetes cluster on AWS (EKS) and we want to expose an external dns for litmus in order for us to access it from outside.

We are using aws ingress controller for this (aws load balancer controller), but it expects services to be NodePort as a prerequisite for creating the application load balancer (alb) and external dns

Here is the doc mentioning this : https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/spec/
`The service, service-2048, must be of type NodePort in order for the provisioned ALB to route to it.`

But we observed that litmus forces services to be ClusterIP if ingress is enabled, it does not honor service.type fields provided in values.yaml while installing helm release when ingress is enabled.

here is link and snippet from one of the service chart:  
1. https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/frontend-svc.yaml 
2. https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/server-svc.yaml
image

### PR DESCRIPTION
**Pull request by Jasstkn**
Signed-off-by: Jasstkn <mariia.kotliarevskaia@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #256 

#### Special notes for your reviewer:

see also PR with documentation update: https://github.com/litmuschaos/litmus-docs/pull/199

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by dchourasia** [comment]
@Jasstkn  thanks a lot for a quick turn around, really appreciate it!
Can you please make the same change for backend server service (server-svc.yaml) as well, this will enable us to create/execute litmus workflows using server APIs directly (without going to UI)

Ingress.yaml already has a rule for backend server service as well.

**Comment by Jasstkn** [comment]
> @Jasstkn thanks a lot for a quick turn around, really appreciate it! Can you please make the same change for backend server service (server-svc.yaml) as well, this will enable us to create/execute litmus workflows using server APIs directly (without going to UI)
> 
> Ingress.yaml already has a rule for backend server service as well.

I'll take a look into that too, thanks

**Comment by Jasstkn** [comment]
@imrajdas hi. could you take a look into this PR please?

**Comment by dchourasia** [comment]
@Jasstkn  thank you for these changes, but I see some breaking changes in **server-svc.yaml** (this file belongs to backend server service and not graphql (mongo) service:

Can you please check following list:

1. line # 14
**Expected**:  type: {{ .Values.portal.server.service.type }}
**Actual** : type: {{ .Values.portal.server.graphqlServer.service.type }}

2. line # 9
**Expected**:  {{- with .Values.portal.server.service.annotations }}
**Actual** : {{- with .Values.portal.server.graphqlServer.service.annotations }}

Appreciate the efforts.

**Comment by Jasstkn** [comment]
> @Jasstkn thank you for these changes, but I see some breaking changes in **server-svc.yaml** (this file belongs to backend server service and not graphql (mongo) service:
> 
> Can you please check following list:
> 
> 1. line # 14
>    **Expected**:  type: {{ .Values.portal.server.service.type }}
>    **Actual** : type: {{ .Values.portal.server.graphqlServer.service.type }}
> 2. line # 9
>    **Expected**:  {{- with .Values.portal.server.service.annotations }}
>    **Actual** : {{- with .Values.portal.server.graphqlServer.service.annotations }}
> 
> Appreciate the efforts!

it's not really a breaking-breaking change but it makes sense to manage service type per actual service. This change updates the general logic. You can see [graphql's ports](https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/server-svc.yaml#L20-L25) in the service template as well.
Could you elaborate a bit what do you mean?

**Comment by dchourasia** [comment]
@Jasstkn I see, yes this perfectly makes sense to have use separate fields for each service type. I was confused if there is any use of portal.server.service.type anymore.

So yes, not a breaking change, we will update our values.yaml accordingly.
thank you!

**Comment by Jasstkn** [comment]
FYI: I'll write additional documentation about upgrade process to the README later today.

**Comment by Jasstkn** [comment]
@imrajdas @ispeakc0de hi folks. Could you review this MR? I added upgrade notes as it's good practice to have some docs for users so they know how to upgrade their chart.

**Review by gdsoumya — APPROVED** [review]

**Review by Jonsy13 — APPROVED** [review]

**Comment by Jasstkn** [comment]
@Jonsy13 hey! thanks for approving it. could you help me with merging this PR and update for docs: https://github.com/litmuschaos/litmus-docs/pull/199?

**Comment by Jonsy13** [comment]
Hi @Jasstkn , Changes looks good to me. Gave a comment on docs PR.
Adding @imrajdas for review as well.

**Review by Adarshkumar14 — APPROVED** [review]

**Review by imrajdas — APPROVED** [review]

**Comment by imrajdas** [comment]
@Jasstkn - Circleci checks are pending. Can you update this PR?

**Comment by Jonsy13** [comment]
Hi @Jasstkn Should i merge this PR?

**Comment by Jasstkn** [comment]
> Hi @Jasstkn Should i merge this PR?

merging this one. thanks! 

fyi: docs PR is also updated.

**Pull request merged**
