### PR TITLE
Remove hardcoded version of chaoscenter in pre-hook job in litmus-agent chart #329

### LINKED ISSUE #329: [Bug] Cannot deploy litmus-agent with older version of chaos center
Hello,

We are try to deploy a litmus agent using the helm chart with a version of the chaoscenter different from 3.0.0-beta8 we got the following error:

```level=error msg="Error response from the server : {\"payload\":{\"errors\":[{\"message\":\"ERROR: CLUSTER  VERSION MISMATCH (need 2.14.x got 3.0.0-beta8)\",\"path\":[\"clusterConnect\"]}],\"data\":null},\"type\":\"data\"}\n"```

I think the problem is coming from here:
https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus-agent/templates/hook-pre-install-job.yaml#L66C27-L66C27
The version `3.0.0-beta8` is hard codded is the template.

### PR DESCRIPTION
**Pull request by Calvinaud**
#### What this PR does / why we need it:

The version of the chaoscenter was hardcoded in the template of the litmus-agent charts that was posing problem when deploying with different version of chaoscenter. The version is now a variable.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #329 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by gdsoumya** [comment]
The main reason to probably hardcode the version was to keep it compatible with the version of the chaos center. There might be other changes needed to the chart/code to work with a different version of the chaos center as things are changing quite rapidly. This modification gives users the impression that this particular chart can work with a different version too which might not be the case.

**Review by gdsoumya — CHANGES_REQUESTED** [review]
The main reason to probably hardcode the version was to keep it compatible with the version of the chaos center. There might be other changes needed to the chart/code to work with a different version of the chaos center as things are changing quite rapidly. This modification gives users the impression that this particular chart can work with a different version too which might not be the case.

Tagging @Jonsy13 to confirm if this change is safe to make

**Comment by Calvinaud** [comment]
Not sure either, but the hardcoded version mean we cannot deploy in 2.14.0 which is still at the moment the no beta version.

In our deployment, we are working with all images in 2.14.0 and we updated the version manually in the agent configmap, will keep updated if we found any issues.

**Comment by Jasstkn** [comment]
> The main reason to probably hardcode the version was to keep it compatible with the version of the chaos center. There might be other changes needed to the chart/code to work with a different version of the chaos center as things are changing quite rapidly. This modification gives users the impression that this particular chart can work with a different version too which might not be the case.
> 
> Tagging @Jonsy13 to confirm if this change is safe to make

Hey. Any update here? For me this change makes sense as long as default is stays the same.

**Comment by gdsoumya** [comment]
> Not sure either, but the hardcoded version mean we cannot deploy in 2.14.0 which is still at the moment the no beta version.
> 
> In our deployment, we are working with all images in 2.14.0 and we updated the version manually in the agent configmap, will keep updated if we found any issues.

The agent helm chart is only supported for 3.x litmus version not 2.x, litmus doesn't provide any support for 2.x in this helm chart.

**Comment by Calvinaud** [comment]
Even if the version 2.x is not supported shouldn't the version still not be hardcoded to have the possible to overwrite it to have the risk of hardcoded incompatibility between chaoscenter and litmus agent (even between two 3.x version) ?

**Comment by Jonsy13** [comment]
I think it should be fine to have version to be provided via `values.yml` as long as we are able to make sure that users know that this agent is not compatible with any other version except 3.x at the moment. @gdsoumya is correct, this was done intentionally. Tagging @ispeakc0de as well to have a look once.

**Comment by Calvinaud** [comment]
>  think the current approach is to have a separate version of the litmus agent that works for a specific 3.x version of chaos center so if you are using a specific version you need to use the specific chart version corresponding to that.

Just a random idea:
If the goal is to bind a version of chaoscenter to the litmus agent chart.  Is using the appVersion of the Charts.yaml as the default value for the VERSION (with the possibility to overwrite in values.yaml) just like the image tag a good idea ?

**Comment by Calvinaud** [comment]
@reviewers Any opinion on my last comment ?

**Review by ispeakc0de — APPROVED** [review]

**Comment by Calvinaud** [comment]
Hello,
@Jasstkn @gdsoumya @Jonsy13 @ispeakc0de 
Retagging you in this PR to have the review/approval.

**Review by Jasstkn — APPROVED** [review]

**Comment by Jasstkn** [comment]
> > think the current approach is to have a separate version of the litmus agent that works for a specific 3.x version of chaos center so if you are using a specific version you need to use the specific chart version corresponding to that.
> 
> Just a random idea: If the goal is to bind a version of chaoscenter to the litmus agent chart. Is using the appVersion of the Charts.yaml as the default value for the VERSION (with the possibility to overwrite in values.yaml) just like the image tag a good idea ?

I don't have a strong opinion about that.

**Comment by nwinstel-insight** [comment]
> The main reason to probably hardcode the version was to keep it compatible with the version of the chaos center. There might be other changes needed to the chart/code to work with a different version of the chaos center as things are changing quite rapidly. This modification gives users the impression that this particular chart can work with a different version too which might not be the case.
> 
> Tagging @Jonsy13 to confirm if this change is safe to make

Does this mean 3.0.0-beta8 is the appropriate version for 3.2.0?

**Comment by Calvinaud** [comment]
Hello, @gdsoumya are you still requesting changes in this PR ?

**Review by gdsoumya — APPROVED** [review]

**Pull request merged**
