### PR TITLE
Priority class name for litmus runner and exporter

### LINKED ISSUE #120: Add support for specifying priorityClassName in litmus operator
We'd like to be able to set the priorityClassName in litmus components (runner, operator and exporter).

### PR DESCRIPTION
**Pull request by blame19**
Signed-off-by: Matteo Maponi <matteo.maponi@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #120

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by blame19** [comment]
@Jasstkn @ispeakc0de  Could you please review?

**Review by Jasstkn — CHANGES_REQUESTED** [review]
Hello, Matteo! Thank you for your contribution to Litmus.
Your PR looks good to me. Before I can approve it, please, update your branch from master and run [helm-docs](https://github.com/norwoodj/helm-docs) against the chart. We use it to keep documentation always updated.

Thank you in advance and let me know if you have any questions.

**Comment by blame19** [comment]
> Hello, Matteo! Thank you for your contribution to Litmus.
> Your PR looks good to me. Before I can approve it, please, update your branch from master and run [helm-docs](https://github.com/norwoodj/helm-docs) against the chart. We use it to keep documentation always updated.
> 
> Thank you in advance and let me know if you have any questions.

Thanks for your answer. I've updated the PR and run helm-docs - let me know what else might be needed.

**Review by Jasstkn — APPROVED** [review]

**Review by ksatchit — APPROVED** [review]

**Comment by ksatchit** [comment]
Thanks for the contrib @blame19 !

**Comment by blame19** [comment]
@ksatchit  Can this be merged?

**Comment by Jasstkn** [comment]
> @ksatchit Can this be merged?

Hi! You should bump helm-chart version and run helm-docs against it ;)

**Comment by blame19** [comment]
> > @ksatchit Can this be merged?
> 
> Hi! You should bump helm-chart version and run helm-docs against it ;)

Which I did, then the PR remained pending until other changes were merged into the main branch :)

**Comment by Jasstkn** [comment]
> > > @ksatchit Can this be merged?
> > 
> > 
> > Hi! You should bump helm-chart version and run helm-docs against it ;)
> 
> Which I did, then the PR remained pending until other changes were merged into the main branch :)

Sorry, I'll ping reviewers after you do it this time :)

**Comment by blame19** [comment]
> > > > @ksatchit Can this be merged?
> > > 
> > > 
> > > Hi! You should bump helm-chart version and run helm-docs against it ;)
> > 
> > 
> > Which I did, then the PR remained pending until other changes were merged into the main branch :)
> 
> Sorry, I'll ping reviewers after you do it this time :)

I pushed, let's review 👍

**Review by Jasstkn — APPROVED** [review]

**Pull request merged**
