### PR TITLE
update chart version in litmus charts

### PR DESCRIPTION
**Pull request by rajdas98**
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>

updating chart version in litmus charts

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Review by Jasstkn — APPROVED** [review]

**Review by Jasstkn — CHANGES_REQUESTED** [review]
@rajdas98 please, update chart name in the circle-ci config litmus-1-x -> litmus-core.

**Review by ksatchit — APPROVED** [review]

**Comment by ksatchit** [comment]
@Jasstkn can you take a look now?

**Comment by rajdas98** [comment]
> @rajdas98 please, update chart name in the circle-ci config litmus-1-x -> litmus-core.

Done @Jasstkn

**Review by Jasstkn — APPROVED** [review]
LGTM now

**Pull request merged**
