### PR TITLE
Adding self cluster as a env in charts

### PR DESCRIPTION
**Pull request by rajdas98**
Adding self cluster as an env in charts
Issue- https://github.com/litmuschaos/litmus/issues/2590

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by Jasstkn — APPROVED** [review]
LGTM 😎

**Comment by rajdas98** [comment]
@Jasstkn Can you merge this PR, if you have the merge access?

**Comment by Jasstkn** [comment]
> @Jasstkn Can you merge this PR, if you have the merge access?

Hi! Sorry I don't have sufficient rights :(

**Comment by rajdas98** [comment]
@ajeshbaby / @ksatchit  Can you approve and merge this PR.

**Review by ajeshbaby — APPROVED** [review]

**Pull request merged**
