### PR TITLE
Added changes for making litmus-agent compatible with 3.0.0-beta7 ChaosCenter

### PR DESCRIPTION
**Pull request by Jonsy13**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Review by gdsoumya — APPROVED** [review]

**Review by Jasstkn — CHANGES_REQUESTED** [review]
chart version must be bumped

**Comment by Jonsy13** [comment]
> chart version must be bumped

Thanks @Jasstkn for pointing this out. Have bumped the version!

**Review by Jasstkn — APPROVED** [review]

**Review by ispeakc0de — APPROVED** [review]

**Comment by Jasstkn** [comment]
@Jonsy13 feel free to merge once you're ready.

**Comment by Jonsy13** [comment]
Just made one commit for changing the control plane version to `3.0.0-beta7` since beta 7 was also released on 17th May to keep it latest!.
Merging now!

**Pull request merged**
