### PR TITLE
Move upgrade agent hook from post to pre

### PR DESCRIPTION
**Pull request by brnck**
#### What this PR does / why we need it:

This PR fixes the issue when you need to upgrade the Litmus version. Bumping the version let's say from 2.9.0 to 2.10.0 helm upgrade fails because the upgrade agent must be run before the actual workloads. Otherwise, litmus-server fails with:

```
k logs litmus-server-
time="2022-06-22T11:33:54Z" level=info msg="Go Version: go1.16.15"
time="2022-06-22T11:33:54Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-06-22T11:33:54Z" level=info msg="Connected To MongoDB"
time="2022-06-22T11:33:54Z" level=fatal msg="control plane needs to be upgraded from version 2.9.0 to 2.10.0"
```

The full discussion can be found at https://kubernetes.slack.com/archives/CNXNB0ZTN/p1655897865498639

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [X] Chart Version bumped

### CODE REVIEW

**Comment by Jasstkn** [comment]
@brnck hi. I noticed that you use the latest version of helm-docs - we haven't updated ours yet. I'll do it today and I'll ping you to update your branch with these changes afterwards.

**Comment by gdsoumya** [comment]
@brnck Just saw this. I think it is expected to be like this, the server fails because it is waiting for the upgrade to happen. We don't want any of the components to be interacting with the database or anything else during an update, that is why a pre-hook will not work as the components will keep running while the upgrade agent executes. So either we need to scale all components to 0 replicas and then run upgrade job or run it as post hook like we do now, where all components wait for the version to match up. Ideally once the upgrade job completes the version should be bumped and on the next restart, the other components will start working as expected.

**Comment by brnck** [comment]
@gdsoumya 

But you do understand that having hook as a post-upgrade is failing because `helm upgrade` times out due to the server being in the crash loop state?

post-upgrade hooks (assuming no --force flags are used) only starts when all deployments are successful. So when the server keeps crashing due to:
```
k logs litmus-server-
time="2022-06-22T11:33:54Z" level=info msg="Go Version: go1.16.15"
time="2022-06-22T11:33:54Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-06-22T11:33:54Z" level=info msg="Connected To MongoDB"
time="2022-06-22T11:33:54Z" level=fatal msg="control plane needs to be upgraded from version 2.9.0 to 2.10.0"
```

That means the post-upgrade hook will not be started. You can check the slack thread I've attached to the description of PR. It should give you more context about the problem

**Comment by Jasstkn** [comment]
> @gdsoumya
> 
> But you do understand that having hook as a post-upgrade is failing because `helm upgrade` times out due to the server being in the crash loop state?
> 
> post-upgrade hooks (assuming no --force flags are used) only starts when all deployments are successful. So when the server keeps crashing due to:
> 
> ```
> k logs litmus-server-
> time="2022-06-22T11:33:54Z" level=info msg="Go Version: go1.16.15"
> time="2022-06-22T11:33:54Z" level=info msg="Go OS/Arch: linux/amd64"
> time="2022-06-22T11:33:54Z" level=info msg="Connected To MongoDB"
> time="2022-06-22T11:33:54Z" level=fatal msg="control plane needs to be upgraded from version 2.9.0 to 2.10.0"
> ```
> 
> That means the post-upgrade hook will not be started. You can check the slack thread I've attached to the description of PR. It should give you more context about the problem

That's correct description of the workflow. Another question - what is expected flow here? I went through the discussion in Slack but didn't catch a lot.

**Comment by gdsoumya** [comment]
> @gdsoumya
> 
> But you do understand that having hook as a post-upgrade is failing because `helm upgrade` times out due to the server being in the crash loop state?
> 
> post-upgrade hooks (assuming no --force flags are used) only starts when all deployments are successful. So when the server keeps crashing due to:
> 
> ```
> k logs litmus-server-
> time="2022-06-22T11:33:54Z" level=info msg="Go Version: go1.16.15"
> time="2022-06-22T11:33:54Z" level=info msg="Go OS/Arch: linux/amd64"
> time="2022-06-22T11:33:54Z" level=info msg="Connected To MongoDB"
> time="2022-06-22T11:33:54Z" level=fatal msg="control plane needs to be upgraded from version 2.9.0 to 2.10.0"
> ```
> 
> That means the post-upgrade hook will not be started. You can check the slack thread I've attached to the description of PR. It should give you more context about the problem

Last when I tested it would work even with post hook not sure if the behavior changed across multiple updates but then we should probably move it from crashing to just waiting or restarting less frequently instead of an aggressive restart. I don't think pre-hook is a solution for this issue.

**Comment by brnck** [comment]
It works when you're not upgrading the chart version. Deploy 2.9.0 on 2.9.0, and post-upgrade will work because the control plane has the same version (2.9.0). Try to upgrade 2.9.0 to 2.10.0, you will get fatal as I got. I've tested this on minikube and in the EKS.

@Jasstkn expected workflow here is to upgrade chart version without fatal

**Comment by gdsoumya** [comment]
@brnck I am not saying you are not right but what I am saying is pre-hook is not the solution, it might've worked now but as I explained we can't have other components interacting with db or any stateful data while an upgrade job is running it will potentially  corrupt the data.

**Pull request closed without merging**
