### PR TITLE
Add pod annotations support

### LINKED ISSUE #404: Add custom annotations support
Hello,

This feature is to support customs pod annotations in the resources deployed by the helm charts.
Custom annotations are sometimes required by organization to add specific information.

### PR DESCRIPTION
**Pull request by Calvinaud**
- Add podAnnotations value to add podannotations on each components
- Add customPodAnnotation value to add podannotations on all components
- bumped version 3.11.1 and regenerated docs

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #404 

#### Special notes for your reviewer:
This PR is inspired by https://github.com/litmuschaos/litmus-helm/pull/274/ but which is inactive for quite a long time. If needed, I can close this PR in favor of the old one if it become active again.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by Calvinaud** [comment]
@Jasstkn @ispeakc0de @imrajdas Tagging you for review / merge of the PR.

**Comment by Calvinaud** [comment]
I can switch to "with" instead of "if" in the deployment if needed.

**Comment by Jonsy13** [comment]
Hi @Calvinaud We just did the 3.13.x release due to that, your PR got some conflicts. Can you please update your PR. We will take this PR before next release so that it come as part of 3.14.x.

**Comment by Calvinaud** [comment]
Hello, @Jonsy13, Update the PR to `3.13.1`.

**Review by Jonsy13 — APPROVED** [review]
Changes looks good! Thanks @Calvinaud

**Review by SarthakJain26 — APPROVED** [review]

**Pull request merged**
