### PR TITLE
Removed litmus-1-x,litmus-portal & litmus-beta from gh-pages

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>

#### What this PR does / why we need it:

**This PR will remove litmus-1-x, litmus-portal & litmus-beta along with entries in `index.yml` from gh-pages.**

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Review by rajdas98 — APPROVED** [review]

**Comment by ksatchit** [comment]
Just to set context on why this is being done: https://artifacthub.io/ reflects the helm packages for litmus and there are too many entries there. The 2-0-0-Beta and litmus-portal are old and unused. 

The change from litmus-1-x to litmus-core needs some announcements to the community, IMO. 

Would like to hear from @Jasstkn on this.

**Comment by Jasstkn** [comment]
> Just to set context on why this is being done: https://artifacthub.io/ reflects the helm packages for litmus and there are too many entries there. The 2-0-0-Beta and litmus-portal are old and unused.
> 
> The change from litmus-1-x to litmus-core needs some announcements to the community, IMO.
> 
> Would like to hear from @Jasstkn on this.

Agree. It's better remove all non-actual charts to avoid misunderstandings.

**Comment by rajdas98** [comment]
@Jasstkn If you're okay with the changes, Can you approve this PR?

**Review by Jasstkn — APPROVED** [review]

**Comment by Jasstkn** [comment]
> @Jasstkn If you're okay with the changes, Can you approve this PR?

We should announce this change to the users who can deploy from these charts. It can cause problems in case they've been deleted.

**Pull request merged**
