### PR TITLE
Add Kubernetes recommanded labels

### PR DESCRIPTION
**Pull request by nlamirault**
#### What this PR does / why we need it:

Next of #85 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rajdas98** [comment]
Thanks, @nlamirault for this PR. Have you tested this PR? I think helm has some issue if we misuse the labels.

**Comment by nlamirault** [comment]
@rajdas98 I use others chart with theses labels. I will try to reinstall this chart.

**Comment by nlamirault** [comment]
I install correctly : 

```yaml
❯ helm list                                                                                  
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                           APP VERSION
litmus          default         1               2021-05-03 12:23:34.678046472 +0200 CEST        deployed        litmus-1.13.8                   1.13.3     
litmus-portal   default         1               2021-05-03 12:23:52.643563947 +0200 CEST        deployed        litmus-2-0-0-beta-2.0.18-Beta5  2.0.0

❯ kubectl get pod -A                                                                         
NAMESPACE            NAME                                                        READY   STATUS    RESTARTS   AGE
default              litmus-6cdfcf874-x6fzv                                      1/1     Running   0          103s
default              litmus-portal-litmus-2-0-0-beta-frontend-6b64bd8696-srdbt   1/1     Running   0          85s
default              litmus-portal-litmus-2-0-0-beta-mongo-0                     1/1     Running   0          85s
default              litmus-portal-litmus-2-0-0-beta-server-5845dbd954-pnmrh     2/2     Running   0          85s
```

**Comment by nlamirault** [comment]
@rajdas98 I push a fix for missing label on portal deployment.

**Review by rajdas98 — APPROVED** [review]
Thanks @nlamirault. LGTM

**Review by ispeakc0de — APPROVED** [review]

**Pull request merged**
