### PR TITLE
Security/fix hardcoded password

### PR DESCRIPTION
**Pull request by Vr00mm**
Signed-off-by: Rémi ZIOLKOWSKI <remi.ziolkowski-ext@pole-emploi.fr>

#### What this PR does / why we need it:
Secrets, DB and JWT are hardcoded.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Review by Jasstkn — CHANGES_REQUESTED** [review]
@Vr00mm hi! CircleCI occasionally doesn't trigger jobs for forks without a new commit, so feel free to squash mine. 
Also, please, take a look into failed jobs: they are all related to the chart that you've changed.

**Review by Jasstkn — COMMENTED** [review]
@Vr00mm could you try to login to https://app.circleci.com/ and check if it requires to allow something? because I don't see pipeline for your commits :( only for mine.

**Comment by Vr00mm** [comment]
> @Vr00mm could you try to login to https://app.circleci.com/ and check if it requires to allow something? because I don't see pipeline for your commits :( only for mine.

I dont know CircleCI, any information on the screenshot ?
image

**Comment by Jasstkn** [comment]
> > @Vr00mm could you try to login to https://app.circleci.com/ and check if it requires to allow something? because I don't see pipeline for your commits :( only for mine.
> 
> @Jasstkn I dont know CircleCI, Do you see any information on the screenshot ? image
> 
> I tried to run manualy the pipeline but it got no effect

What if you navigate to your fork instead of litmus organization?

**Comment by Vr00mm** [comment]
> > > @Vr00mm could you try to login to https://app.circleci.com/ and check if it requires to allow something? because I don't see pipeline for your commits :( only for mine.
> > 
> > 
> > @Jasstkn I dont know CircleCI, Do you see any information on the screenshot ? image
> > I tried to run manualy the pipeline but it got no effect
> 
> What if you navigate to your fork instead of litmus organization?

Wow...
image

Here we go ...

**Comment by Vr00mm** [comment]
Well, it's pretty work now ....

Thanks for the solution and apologize for all that lost time...

**Comment by ksatchit** [comment]
@Vr00mm some minor conflicts you would like to fix (we made some vers changes :) )

**Comment by ksatchit** [comment]
Do you think this change also benefits by some readme/doc changes as well? WDYT @Jasstkn

**Review by rajdas98 — CHANGES_REQUESTED** [review]
HI @Vr00mm , Can you update the chart version?

**Review by rajdas98 — APPROVED** [review]

**Review by ksatchit — APPROVED** [review]

**Comment by ksatchit** [comment]
Thanks @Vr00mm !!

**Pull request merged**
