### PR TITLE
Add security context for init container for portal server

### PR DESCRIPTION
**Pull request by stephen-harris**
#### What this PR does / why we need it:

Add's support for configuring the securityContext of the litmus-server init container. In environments where runAsNonRoot is automatically set to `true` the init container fails to start because the `runAsUser` is not specified. 

This also aligns the configuration of the init container with the other containers in this deployment.

#### Which issue this PR fixes

n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by Jasstkn — APPROVED** [review]

**Comment by rajdas98** [comment]
@stephen-harris Have you tested it. I think mongo won't run with these fields in the security context
```
  runAsUser: 2000
  runAsNonRoot: true
```

**Comment by Jasstkn** [comment]
@imrajdas hi. could you take a loot into this PR?

**Comment by Jasstkn** [comment]
@imrajdas hi. Can you evaluate if this is still something that we want to have?

**Comment by imrajdas** [comment]
@Jasstkn - There is a merge conflict

**Comment by Jasstkn** [comment]
> @Jasstkn - There is a merge conflict

@imrajdas Hi. I was asking if we want to have this PR opened or it's not up-to-date and we should close it?

**Comment by Jasstkn** [comment]
@stephen-harris hi! do you want to continue working on this? I think that it's enough to make security context configurable. then users can decide if they want to configure it or not?

**Comment by Jasstkn** [comment]
No activity in this PR. I'm going to close it in favor of https://github.com/litmuschaos/litmus-helm/pull/332

**Pull request closed without merging**
