### PR TITLE
Added latest CRD validations,and clusterrole

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by rahulchheda** [comment]
@Jasstkn Are the changes sufficient?

**Comment by Jasstkn** [comment]
@rahulchheda bump tags pls : https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/values.yaml#L15

**Comment by Jasstkn** [comment]
And here too: https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/README.md

**Comment by rahulchheda** [comment]
@Jasstkn Made the changes, can you take a look again?

**Comment by Jasstkn** [comment]
LGTM

**Pull request merged**
