### PR TITLE
add missing kubernetes-chaos service account permissions

### LINKED ISSUE #201: k8s-chaos-admin service account permissions
In this file, the cluster role is missing a few permissions required for some of the experiments: https://github.com/litmuschaos/litmus-helm/blob/7537fcd3f8caa4921b68525842707bc22c092b89/charts/kubernetes-chaos/templates/clusterrole.yaml

- resources: `networkpolicies`,`replicationcontrollers`, `deploymentconfigs`, `rollouts`
- apiGroups: `argoproj.io`, `apps.openshift.io"`

### PR DESCRIPTION
**Pull request by calvinbui**
Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #201 

#### Special notes for your reviewer:

Places the permissions are used:

networkpolicies:
- pod-network-partition.yaml

replicationcontrollers:

- container-kill.yaml
- pod-dns-spoof.yaml
- pod-dns-error.yaml
- pod-network-latency.yaml
- pod-network-duplication.yaml
- pod-network-corruption.yaml
- disk-fill.yaml
- pod-network-loss.yaml
- pod-cpu-hog-exec.yaml
- pod-delete.yaml
- pod-memory-hog-exec.yaml
- pod-io-stress.yaml
- pod-memory-hog.yaml
- pod-cpu-hog.yaml

deploymentconfigs:
- pod-dns-spoof.yaml
- pod-network-latency.yaml
- pod-dns-error.yaml
- pod-delete.yaml
- pod-network-corruption.yaml
- pod-memory-hog-exec.yaml
- pod-cpu-hog-exec.yaml
- pod-io-stress.yaml
- pod-memory-hog.yaml
- pod-network-loss.yaml
- pod-cpu-hog.yaml
- pod-network-duplication.yaml
- disk-fill.yaml
- container-kill.yaml

rollouts:

- pod-dns-spoof.yaml
- pod-dns-error.yaml
- pod-network-latency.yaml
- pod-network-duplication.yaml
- disk-fill.yaml
- pod-network-corruption.yaml
- pod-network-loss.yaml
- pod-cpu-hog-exec.yaml
- pod-delete.yaml
- pod-memory-hog-exec.yaml
- pod-io-stress.yaml
- pod-memory-hog.yaml
- pod-cpu-hog.yaml
- container-kill.yaml

apps.openshift.io:
- pod-dns-spoof.yaml
- pod-dns-error.yaml
- pod-network-latency.yaml
- pod-network-duplication.yaml
- pod-network-loss.yaml
- pod-network-corruption.yaml
- disk-fill.yaml
- pod-cpu-hog-exec.yaml
- pod-delete.yaml
- pod-memory-hog-exec.yaml
- pod-io-stress.yaml
- pod-cpu-hog.yaml
- pod-memory-hog.yaml
- container-kill.yaml

argoproj.io:

- pod-dns-spoof.yaml
- pod-memory-hog-exec.yaml
- pod-dns-error.yaml
- pod-network-latency.yaml
- pod-network-corruption.yaml
- disk-fill.yaml
- pod-network-loss.yaml
- pod-network-duplication.yaml
- pod-cpu-hog-exec.yaml
- pod-delete.yaml
- pod-io-stress.yaml
- pod-memory-hog.yaml
- container-kill.yaml
- pod-cpu-hog.yaml

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by calvinbui** [comment]
@Jasstkn @ksatchit following up on this

**Comment by calvinbui** [comment]
> @Jasstkn @ksatchit following up on this

Following up again

**Comment by calvinbui** [comment]
why do i bother.

**Comment by Jasstkn** [comment]
@calvinbui hi. sorry for the delay. By some reasons I lost your PR. Could you bump chart version and run helm-docs? I'll approve and merge it then.

**Comment by calvinbui** [comment]
@Jasstkn ready

**Pull request merged**
